package storage

import (
	"agentlabs.local/abv/domain"
	"context"
)

type CatalogWriteSet struct {
	Permission *domain.PermissionDefinition
	Scope      *domain.ScopeDefinition
	// PlatformPermission registers a permission in a namespace the platform
	// defines and no application can claim. PlatformNamespace is that namespace,
	// and it lands in key3 where an application permission puts its application.
	PlatformPermission *domain.PermissionDefinition
	PlatformNamespace  string
	// ApplicationRole publishes a role the application ships to every tenant.
	// ApplicationRoleIssued says whether its id was generated by this call,
	// which decides whether an existing id is a conflict or a new revision.
	ApplicationRole       *domain.RoleContent
	ApplicationRoleIssued bool
	// PermissionStatus updates an existing definition's active flag. It is
	// distinct from Permission, which inserts a new one: a status change must
	// never create an identifier, and a registration must never overwrite one.
	PermissionStatus *domain.PermissionDefinition
}

type CatalogProvider interface {
	ReadCatalog(context.Context, domain.Application, func(domain.Catalog) error) error
	UpdateCatalog(context.Context, domain.Application, func(domain.Catalog) (CatalogWriteSet, error)) error
	// UpdatePlatformCatalog writes a record at the platform boundary. It takes a
	// namespace rather than an application because a platform namespace is not
	// one — the application registry reserves those names so it never can be —
	// and so there is no applications row to read a generation from.
	//
	// Every application's generation is bumped instead, which is the correct
	// semantic rather than a workaround: a platform permission appears in every
	// application's catalog, so a write to one invalidates every cached view.
	UpdatePlatformCatalog(context.Context, string, func() (CatalogWriteSet, error)) error
}
